spring.application.name=smart-career-system
server.port=8085

# 1. Added a command to auto-create the database on your machine if it doesn't exist
spring.datasource.url=jdbc:mysql://localhost:3306/smart_career_db?createDatabaseIfNotExist=true
spring.datasource.username=root

# ==========================================
# TEAM DATABASE PASSWORDS
# -> Uncomment your specific password below.
# -> Leave the other team members commented out!
# ==========================================

# Emmanuel's DB Password
spring.datasource.password=Emanuel@mafalo77

# Destiny's DB Password
#spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

##Security
jwt.secret=ThisIsAVeryLongSecretKeyForDevelopmentOnlyChangeMe12345678901234567890
jwt.expiration=86400000